kind = "mobile"
previewPath = "/"
title = "notify her"
version = "1.0.0"
id = "artifacts/notify-her"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 18120

[services.development]
run = "pnpm --filter @workspace/notify-her run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/notify-her", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/notify-her", "run", "serve" ]

[services.env]
PORT = "18120"
BASE_PATH = "/"
